// Generated by scripts/export_model.py - do not edit by hand.
#pragma once
#include <cstddef>

namespace model_weights {
constexpr bool kIsTrained = true;
constexpr std::size_t kInputDim = 8;
constexpr std::size_t kNumClasses = 2;
constexpr std::size_t kNumLayers = 2;

// Output interpretation:
// - kBinaryLogit: final neuron logistic -> P(class[kLogitPositiveClass]); other class = 1 - P.
// - kMultiClass: apply softmax to final layer logits; probabilities align with kClassNames order.
enum class OutputType { kBinaryLogit, kMultiClass };
constexpr OutputType kOutputType = OutputType::kBinaryLogit;
constexpr std::size_t kLogitPositiveClass = 1;

static const char* const kClassNames[kNumClasses] = {
    "erasor", "screw"
};

static const char* const kFeatureNames[kInputDim] = {
    "band_0", "band_1", "band_2", "band_3",
    "decay_ms", "peak_dev_mg", "peak_mag_mg", "rms_dev_mg"
};

static const float kImputerMedian[kInputDim] = {
    951481856.00000000f, 539772480.00000000f, 291880256.00000000f, 301621632.00000000f, 4.21686745f, 9301.70703125f, 11309.35156250f, 1395.42053223f
};

static const float kScalerMean[kInputDim] = {
    2416637184.00000000f, 990064512.00000000f, 466347968.00000000f, 437218048.00000000f, 7.20740128f, 9239.65039062f, 11245.69921875f, 1298.53515625f
};

static const float kScalerScale[kInputDim] = {
    3966057472.00000000f, 1124948352.00000000f, 474453888.00000000f, 397500224.00000000f, 8.26920605f, 1523.97705078f, 1523.88317871f, 468.45281982f
};

struct Layer {
    std::size_t input_dim;
    std::size_t output_dim;
    const float* weights; // row-major [output][input]
    const float* biases;  // length == output_dim
};

static const float kLayer0Weights[] = {
    -0.54078126f, -0.49041209f, -0.85799986f, -0.23456761f, 0.17474738f, 0.19662005f, -0.14435580f, 0.83630306f,
    0.17437044f, 0.12473007f, 0.51588625f, -0.62546217f, 0.16325225f, 0.14316492f, -0.05314547f, 0.58367234f,
    -0.31695276f, -0.51945549f, 0.25235519f, 0.52143902f, -0.65248865f, -0.26368168f, -0.56556940f, -0.42658600f,
    0.87717193f, -0.10487841f, 0.74855697f, -0.21324466f, 0.55766565f, -0.93385822f, -0.89026105f, 0.97548121f,
    -0.21714124f, 0.10849746f, -0.26025954f, 0.03000636f, -0.79949141f, -0.07314225f, -0.35373682f, 0.66113609f,
    -0.24706313f, -0.20243829f, -0.24748610f, 0.21679288f, 0.66594112f, -0.07166956f, 0.23935777f, -0.13170964f,
    -0.66095948f, -0.36120945f, 0.06050970f, 0.20704082f, 0.11583041f, 0.09292359f, -0.32180634f, 0.14757465f,
    0.47569481f, -0.23565519f, 0.08084771f, 0.24072288f, -0.36258441f, -0.10158324f, -0.23401988f, 0.52546096f,
    0.04422010f, 0.15975071f, -0.26593351f, -0.69152153f, -0.21433432f, 0.15224622f, 0.17134768f, 0.62024945f,
    0.08166456f, 0.09776604f, -0.16197526f, -0.56939024f, 0.38412681f, -0.32200959f, -0.54688114f, 0.97778004f,
    -0.81709844f, -0.53950542f, -0.67915344f, -0.15489103f, -0.04085043f, -0.27434212f, 0.01875648f, -0.57288069f,
    0.76644683f, 0.23072404f, 0.62511748f, -0.19531316f, 0.44981167f, -0.07400888f, -0.03305575f, -0.08813108f,
    -0.03214494f, -0.20832340f, -0.29687193f, 0.05270899f, -0.04938518f, 0.36323193f, -0.16605234f, -0.71870267f,
    -0.62692827f, -0.75632590f, -0.13888013f, 0.00589837f, -0.79277748f, 0.21321678f, -0.26863730f, -0.49988228f,
    -0.92183757f, 0.25161374f, -0.22482532f, 0.16261162f, 0.15264545f, 0.35578513f, -0.12665714f, 0.68222541f,
    -0.45538044f, -0.11563102f, -0.10747193f, 0.06347238f, -0.22309554f, -0.08415134f, -0.41647530f, 0.20035520f
};
static const float kLayer0Bias[] = {
    -0.13403288f, 0.28734988f, -0.52328891f, 0.30574107f, 0.19419961f, -0.22982676f, 0.24394704f, 0.48229048f,
    0.33305782f, 0.71593225f, 0.06084600f, 0.82226878f, 0.24164414f, -0.04460147f, 0.43115336f, -0.44572774f
};

static const float kLayer1Weights[] = {
    -0.69758159f, -0.81204975f, 0.74186617f, -0.47439712f, -0.95879549f, -0.25470099f, 0.30442172f, -1.05865526f,
    -0.72338742f, -0.32242584f, 1.00986111f, -0.58675092f, 0.72165406f, 0.76119161f, -0.77046746f, 0.11455631f
};
static const float kLayer1Bias[] = {
    -0.40901956f
};

static const Layer kLayers[kNumLayers] = {
    { 8, 16, kLayer0Weights, kLayer0Bias },
    { 16, 1, kLayer1Weights, kLayer1Bias }
};

} // namespace model_weights
